version: '3.7'
services:
  authorization-server:
    container_name: authorization-server-container
    build: authorization-server/
    image: fdlessard/authorization-server-image:latest
    ports:
      - 8081:8081
  resource-server:
    container_name: resource-server-container
    build: resource-server/
    image: fdlessard/resource-server-image:latest
    depends_on:
      - authorization-server
    ports:
      - 8080:8080