server:
  port: 8080

logging:
  level.io.fdlessard.codebites.oauth2.authorization: DEBUG
  level.root: DEBUG

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
    resource:
      token-info-uri: https://localhost:8442/oauth/check_token
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiA/K94JiffQ0nauFq0tC
          Pg3txZAm2iKWwlZwH7HdBXFj9P5pINNBBiTBSZE9BE4Urk4VzL1eXfxVfovRYhho
          fcjcNIr3yzAex9Gj/UIq+08euHJqajoDmdEvmchlRPJTXjZG2mSES7VI/e166VZU
          5JMhNSnKdUFSOR8muRhzi/nlV2wpoa9Otc5VyHc86giH8VmU0o/fzEHv50Np3cRO
          HyMdUipWecZS1IiCkvROjhsi6mylBFimjtuK8RtHuUPOME7Yml8iYzWYW6iSVmd0
          HBVbKSMepDtcunPZt1t3ep/94E81DDUTs/8h61xlX1YjAbNkc2lsH1xIsU+OckBx
          RQIDAQAB
          -----END PUBLIC KEY-----

