server:
  port: 8081

logging:
  level.io.fdlessard.codebites.oauth2.authorization: DEBUG
  level.root: DEBUG


jwtKeyStore:
  file: mykey.jks
  password: mypass
  key: mykey
#  key-pair-password: changeme

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      scopes: all
      authorizedGrantTypes: authorization_code, refresh_token, password, implicit, client_credentials
      accessTokenValiditySeconds: 3600
      refreshTokenValiditySeconds: 3600

spring:
  output:
    ansi:
      enabled: always
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: on
      path: /h2-console
      settings:
        trace: on
  datasource:
    platform: h2
    url: jdbc:h2:mem:db;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


---
# Development profile

spring:
  profiles: development
  h2:
    console:
      enabled: on
      path: /h2-console
      settings:
        trace: on
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


---
# Integration test profile

spring:
  profiles: integration
  h2:
    console:
      enabled: on
      path: /h2-console
      settings:
        trace: on
  datasource:
    platform: h2
    url: jdbc:h2:mem:db;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true